[toolchain]
anchor_version = "0.32.0"
solana_version = "2.1.0"

[features]
seeds = true
skip-lint = false

[programs.devnet]
sol_sensor = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf --manifest-path=programs/sol-sensor/Cargo.toml"
