# [toolchain]
# anchor_version = "0.32.0"
# solana_version = "2.1.0"

[features]
seeds = true
skip-lint = false

[programs.devnet]
sol_sensor = "ETu1YLCnZyeeWBYYLSFXLNncJa4AgaHaZQ8JSUxTEosJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf --manifest-path=sol-sensor/Cargo.toml"
