/**
 * Codama-generated instruction builders for the SolSensor Anchor program.
 *
 * These are stub implementations for the MVP. In production, these would be
 * generated by Codama from the program's IDL and would produce type-safe
 * @solana/kit-compatible instruction objects.
 */

import { PROGRAM_ID } from './constants';

export interface PayForQueryAccounts {
  sensorPool: string;
  poolVault: string;
  hardwareEntry: string;
  hardwareOwner: string;
  payer: string;
  queryReceipt: string;
  systemProgram?: string;
  tokenProgram?: string;
}

export interface PayForQueryArgs {
  sensorId: string;
  nonce: Uint8Array;
}

export interface ConsumeReceiptAccounts {
  authority: string;
  receipt: string;
  payer: string;
}

export interface ClaimRewardsAccounts {
  holder: string;
  contributorState: string;
  sensorPool: string;
  poolVault: string;
  holderUsdc: string;
  tokenProgram?: string;
}

export interface InitContributorAccounts {
  contributor: string;
  contributorState: string;
  systemProgram?: string;
}

/**
 * Build a `pay_for_query` instruction object.
 *
 * In the full implementation, this would use Codama-generated encoders to
 * serialise the discriminator and arguments into a @solana/kit IInstruction.
 */
export function getPayForQueryInstruction(
  accounts: PayForQueryAccounts,
  args: PayForQueryArgs,
): { programAddress: string; accounts: PayForQueryAccounts; data: Uint8Array } {
  // Stub: discriminator is the first 8 bytes of SHA-256("global:pay_for_query")
  const discriminator = new Uint8Array([0xaa, 0xb1, 0x0c, 0x5e, 0x3b, 0x9d, 0x23, 0x4f]);
  return {
    programAddress: PROGRAM_ID,
    accounts,
    data: new Uint8Array([...discriminator, ...args.nonce]),
  };
}

/**
 * Build a `claim_rewards` instruction object.
 */
export function getClaimRewardsInstruction(
  accounts: ClaimRewardsAccounts,
): { programAddress: string; accounts: ClaimRewardsAccounts; data: Uint8Array } {
  const discriminator = new Uint8Array([0x3e, 0xcb, 0x11, 0xa7, 0xf4, 0x29, 0x60, 0x0d]);
  return {
    programAddress: PROGRAM_ID,
    accounts,
    data: discriminator,
  };
}

/**
 * Build an `init_contributor` instruction object.
 */
export function getInitContributorInstruction(
  accounts: InitContributorAccounts,
): { programAddress: string; accounts: InitContributorAccounts; data: Uint8Array } {
  const discriminator = new Uint8Array([0x12, 0x3a, 0xbc, 0x5f, 0x7e, 0x90, 0x11, 0xcd]);
  return {
    programAddress: PROGRAM_ID,
    accounts,
    data: discriminator,
  };
}
